"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['automationFrontEnd.py']
DATA_FILES = ['CapSheet.xlsx']
OPTIONS = {'argv_emulation': True, 'packages': ['openpyxl']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
